//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseRatingAppraiser.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyPerfomance
    {
        public int Id { get; set; }
        public int IdCompany { get; set; }
        public int IdCriterion { get; set; }
        public string Month { get; set; }
        public int Year { get; set; }
        public decimal Value { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Criterion Criterion { get; set; }
    }
}
