//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseRatingAppraiser.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnterpriseRatingAppraiserContainer : DbContext
    {
        public EnterpriseRatingAppraiserContainer()
            : base("name=EnterpriseRatingAppraiserContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> CompanySet { get; set; }
        public virtual DbSet<CompanyPerfomance> CompanyPerfomanceSet { get; set; }
        public virtual DbSet<Criterion> CriterionSet { get; set; }
        public virtual DbSet<Rating> RatingSet { get; set; }
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<TypeOfEconomicActivity> TypeOfEconomicActivitySet { get; set; }
        public virtual DbSet<OwnershipForm> OwnershipFormSet { get; set; }
    }
}
